services:
  - type: web
    name: brightpath-grade-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/web_app.py
    plan: free
    branch: main
